version: '3.7'
services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      # Linux only
      # - /var/run/user/1000/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - proxy

  traefik:
    depends_on:
      - socket-proxy
    image: traefik:2.6
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - proxy
    volumes:
      # Traefik configuration file
      - ./traefik.yml:/traefik.yml

  redis:
    image: bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.redis.rule=Host(`redis.docker.localhost`)'
      - 'traefik.http.routers.redis.entrypoints=http'

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    scale: 3
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)'
      - 'traefik.http.routers.whoami.entrypoints=http'

  ping:
    build:
      context: apps/ping/
      dockerfile: Dockerfile
    scale: 1
    networks:
      - proxy
    ports:
      - '3000:3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pingservices.rule=Host(`ping.docker.localhost`)'
      - 'traefik.http.routers.pingservices.entrypoints=http'

  fastify:
    build:
      context: apps/fastify-redis/
      dockerfile: Dockerfile
    scale: 1
    networks:
      - proxy
    ports:
      - '4040:4040'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fastify.rule=Host(`fastify.docker.localhost`)'
      - 'traefik.http.routers.fastify.entrypoints=fastify'

networks:
  proxy:
    external: true
