api:
  insecure: true
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
  backend:
    address: ':3000'
  fastify:
    address: ':4040'
  redis:
    address: ':6379'

providers:
  docker:
    endpoint: 'tcp://socket-proxy:2375'
    watch: true
    exposedbydefault: false

ping: {}
