api:
  insecure: true
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
  zipkin:
    address: ':9411'
  redis:
    address: ':6379'

providers:
  docker:
    endpoint: 'tcp://socket-proxy:2375'
    watch: true
    exposedbydefault: false
    network: 'proxy'
  redis:
    endpoints:
      - 'redis:6379'

tracing:
  serviceName: traefik
  spanNameLimit: 150
  zipkin:
    httpEndpoint: http://zipkin.docker.localhost:9411/api/v2/spans
    sameSpan: true
